apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-101
  labels:
    app: kubernetes-101
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes-101
  template:
    metadata:
      labels:
        app: kubernetes-101
    spec:
      containers:
        - name: kubernetes-101
          image: kubernetes-101:v1
          ports:
            - name: http
              containerPort: 4200
